//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfKozhuhov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        static Employee emp;
        public static Employee CreateEmployee(int Id, string surname, string name, string Patroymic, int titleID)
        {
            emp = new Employee();
            emp.Id = Id;
            emp.Surname = surname;
            emp.Name = name;
            emp.Patronymic = Patroymic;
            emp.TitleID = titleID;
            emp.Telephone = "не задано";
            emp.Email = "не задано";
            return emp;
        }
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> BirstDate { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int TitleID { get; set; }
    
        public virtual Title Title { get; set; }
    }
}
